# Generated by Django 4.2.6 on 2024-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudall', '0003_crud_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
